[build]
buildCommand = "bun run build:server"

[deploy]
startCommand = "sleep 3 && cd packages/server && bun start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "NEVER"
drainingSeconds = 60
