name: autofix.ci

on:
  pull_request:
    branches: ["main"]

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun fix
      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
